version: '3.8'

services:
  frontend:
    build:
      context: ./front
    ports:
      - "5173"
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - OPEN_AI_ORG=${OPEN_AI_ORG}
      - OPEN_AI_KEY=${OPEN_AI_KEY}
